version: "3"

services:
  ui:
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    image: node:16.14.2-alpine3.15
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/opt/ui
    working_dir: /opt/ui

  server:
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    image: node:16.14.2-alpine3.15
    links:
      - database:database
    ports:
      - "8080:8080"
    volumes:
      - ./server:/opt/server
    working_dir: /opt/server

  database:
    platform: linux/x86_64
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: hipages
      MYSQL_DATABASE: hipages
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
